export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const INCREASE_ITEM_IN_CART = 'INCREASE_ITEM_IN_CART';
export const DECREASE_ITEM_IN_CART = 'DECREASE_ITEM_IN_CART';
export const REMOVE_ITEM_IN_CART = 'REMOVE_ITEM_IN_CART';
export const CLEAR_CART = 'CLEAR_CART';
